// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package outboxrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FoundationOutboxEvent struct {
	ID        int64
	Topic     string
	Key       string
	Payload   []byte
	Headers   []byte
	CreatedAt pgtype.Timestamptz
}
