// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package outboxrepo

import (
	"encoding/json"
	"time"
)

type FoundationOutboxEvent struct {
	ID            int64
	Topic         string
	Key           string
	ProtoName     string
	Payload       []byte
	Headers       json.RawMessage
	CorrelationID string
	CreatedAt     time.Time
}
