// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: errors/proto/errors.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InternalError) Reset() {
	*x = InternalError{}
	mi := &file_errors_proto_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalError) ProtoMessage() {}

func (x *InternalError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalError.ProtoReflect.Descriptor instead.
func (*InternalError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{0}
}

type UnauthenticatedError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnauthenticatedError) Reset() {
	*x = UnauthenticatedError{}
	mi := &file_errors_proto_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnauthenticatedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnauthenticatedError) ProtoMessage() {}

func (x *UnauthenticatedError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnauthenticatedError.ProtoReflect.Descriptor instead.
func (*UnauthenticatedError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{1}
}

type StaleObjectError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind            string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ActualVersion   int32  `protobuf:"varint,3,opt,name=actual_version,json=actualVersion,proto3" json:"actual_version,omitempty"`
	ExpectedVersion int32  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
}

func (x *StaleObjectError) Reset() {
	*x = StaleObjectError{}
	mi := &file_errors_proto_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleObjectError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleObjectError) ProtoMessage() {}

func (x *StaleObjectError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleObjectError.ProtoReflect.Descriptor instead.
func (*StaleObjectError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{2}
}

func (x *StaleObjectError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StaleObjectError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaleObjectError) GetActualVersion() int32 {
	if x != nil {
		return x.ActualVersion
	}
	return 0
}

func (x *StaleObjectError) GetExpectedVersion() int32 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type NotFoundError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NotFoundError) Reset() {
	*x = NotFoundError{}
	mi := &file_errors_proto_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFoundError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFoundError) ProtoMessage() {}

func (x *NotFoundError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFoundError.ProtoReflect.Descriptor instead.
func (*NotFoundError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{3}
}

func (x *NotFoundError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NotFoundError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PermissionDeniedError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *PermissionDeniedError) Reset() {
	*x = PermissionDeniedError{}
	mi := &file_errors_proto_errors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDeniedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDeniedError) ProtoMessage() {}

func (x *PermissionDeniedError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDeniedError.ProtoReflect.Descriptor instead.
func (*PermissionDeniedError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionDeniedError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PermissionDeniedError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionDeniedError) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type InvalidArgumentError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind       string                            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id         string                            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Violations []*InvalidArgumentError_Violation `protobuf:"bytes,3,rep,name=violations,proto3" json:"violations,omitempty"`
}

func (x *InvalidArgumentError) Reset() {
	*x = InvalidArgumentError{}
	mi := &file_errors_proto_errors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidArgumentError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidArgumentError) ProtoMessage() {}

func (x *InvalidArgumentError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidArgumentError.ProtoReflect.Descriptor instead.
func (*InvalidArgumentError) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidArgumentError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InvalidArgumentError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvalidArgumentError) GetViolations() []*InvalidArgumentError_Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type InvalidArgumentError_Violation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field       string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *InvalidArgumentError_Violation) Reset() {
	*x = InvalidArgumentError_Violation{}
	mi := &file_errors_proto_errors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidArgumentError_Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidArgumentError_Violation) ProtoMessage() {}

func (x *InvalidArgumentError_Violation) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_errors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidArgumentError_Violation.ProtoReflect.Descriptor instead.
func (*InvalidArgumentError_Violation) Descriptor() ([]byte, []int) {
	return file_errors_proto_errors_proto_rawDescGZIP(), []int{5, 0}
}

func (x *InvalidArgumentError_Violation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *InvalidArgumentError_Violation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_errors_proto_errors_proto protoreflect.FileDescriptor

var file_errors_proto_errors_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x0f,
	0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x16, 0x0a, 0x14, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x6c,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd2, 0x01, 0x0a,
	0x14, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x51, 0x0a, 0x0a, 0x76, 0x69, 0x6f,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x43, 0x0a, 0x09,
	0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errors_proto_errors_proto_rawDescOnce sync.Once
	file_errors_proto_errors_proto_rawDescData = file_errors_proto_errors_proto_rawDesc
)

func file_errors_proto_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_proto_errors_proto_rawDescData)
	})
	return file_errors_proto_errors_proto_rawDescData
}

var file_errors_proto_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_errors_proto_errors_proto_goTypes = []any{
	(*InternalError)(nil),                  // 0: foundation.errors.InternalError
	(*UnauthenticatedError)(nil),           // 1: foundation.errors.UnauthenticatedError
	(*StaleObjectError)(nil),               // 2: foundation.errors.StaleObjectError
	(*NotFoundError)(nil),                  // 3: foundation.errors.NotFoundError
	(*PermissionDeniedError)(nil),          // 4: foundation.errors.PermissionDeniedError
	(*InvalidArgumentError)(nil),           // 5: foundation.errors.InvalidArgumentError
	(*InvalidArgumentError_Violation)(nil), // 6: foundation.errors.InvalidArgumentError.Violation
}
var file_errors_proto_errors_proto_depIdxs = []int32{
	6, // 0: foundation.errors.InvalidArgumentError.violations:type_name -> foundation.errors.InvalidArgumentError.Violation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errors_proto_errors_proto_init() }
func file_errors_proto_errors_proto_init() {
	if File_errors_proto_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_proto_errors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_errors_proto_depIdxs,
		MessageInfos:      file_errors_proto_errors_proto_msgTypes,
	}.Build()
	File_errors_proto_errors_proto = out.File
	file_errors_proto_errors_proto_rawDesc = nil
	file_errors_proto_errors_proto_goTypes = nil
	file_errors_proto_errors_proto_depIdxs = nil
}
